export default {
  INTRODUCAO: '1',
  INTRODUCAO_DIALOG: '2',
  MICROMUNDO_I: '3',
  MICROMUNDO_I_DIALOG: '4',
  MICROMUNDO_II: '5',
  MICROMUNDO_II_DIALOG: '6',
  MICROMUNDO_III: '7',
  MICROMUNDO_III_DIALOG: '8',
  MICROMUNDO_IV: '9',
  MICROMUNDO_IV_DIALOG: '10',
  CONSIDERACOES_FINAIS: '11',
  CONSIDERACOES_FINAIS_DIALOG: '12'
}
