export default {
  INTRODUCAO: '4',
  INTRODUCAO_DIALOG: '3',
  MICROMUNDO_I: '8',
  MICROMUNDO_I_DIALOG: '3',
  MICROMUNDO_II: '12',
  MICROMUNDO_II_DIALOG: '3',
  MICROMUNDO_III: '8',
  MICROMUNDO_III_DIALOG: '3',
  MICROMUNDO_IV: '12',
  MICROMUNDO_IV_DIALOG: '3',
  CONSIDERACOES_FINAIS: '1',
  CONSIDERACOES_FINAIS_DIALOG: '2'
}
